from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('friends', views.friends, name='friends'),
    path('create', views.create, name='create'),
    path('ris', views.ris, name = 'ris'),
    path('dc', views.dc, name = 'dc'),
    path('prob', views.prob, name = 'prob'),
    path('xman', views.xman, name = 'xman'),
    path('fantastic', views.fantastic, name='fantastic'),
    path('stgal', views.stgal, name='stgal'),
    path('spider', views.spider, name='spider'),
    path('iron', views.iron, name='iron'),
    path('hulk', views.hulk, name='hulk'),
    path('cap', views.cap, name='cap'),
    path('panter', views.panter, name='panter'),
    path('tor', views.tor, name='tor'),
    path('com1', views.com1, name='com1'),
    path('com2', views.com2, name='com2'),
    path('com3', views.com3, name='com3'),
    path('com4', views.com4, name='com4'),
    path('com5', views.com5, name='com5'),
    path('com6', views.com6, name='com6'),
    path('com7', views.com7, name='com7'),
    path('com8', views.com8, name='com8'),
    path('com9', views.com9, name='com9'),
    path('com10', views.com10, name='com10'),
    path('com11', views.com11, name='com11'),
    path('com12', views.com12, name='com12'),
    path('com13', views.com13, name='com13'),
    path('com1a', views.com1a, name='com1a'),
    path('com2a', views.com2a, name='com2a'),
    path('com3a', views.com3a, name='com3a'),
    path('com4a', views.com4a, name='com4a'),
    path('com5a', views.com5a, name='com5a'),
    path('com6a', views.com6a, name='com6a'),
    path('com7a', views.com7a, name='com7a'),
    path('com8a', views.com8a, name='com8a'),
    path('com9a', views.com9a, name='com9a'),
    path('com10a', views.com10a, name='com10a'),
    path('com11a', views.com11a, name='com11a'),
    path('com12a', views.com12a, name='com12a'),
    path('com13a', views.com13a, name='com13a'),

]